nelmio_cors:
    paths:
        '^/api/':
            allow_origin:
                - 'https://jpci.vercel.app'
                - 'https://m.j-pci.com'
            allow_headers:
                - 'Content-Type'
                - 'Authorization'
            allow_methods:
                - 'GET'
                - 'OPTIONS'
                - 'POST'
                - 'PUT'
                - 'PATCH'
                - 'DELETE'
            expose_headers:
                - 'Link'
            max_age: 3600